### PR TITLE
UA locale

### PR DESCRIPTION
**Pull request by OleksiiGerasymenko**
Ukraine locale

### CODE REVIEW

**Comment by ALERTua** [comment]
I would love to see my language in my favorite Python module!

**Comment by Secrus** [comment]
> I would love to see my language in my favorite Python module!

I would love to merge it, but as you can see, CI currently fails. Once it's fixed, it can be merged.

**Comment by OleksiiGerasymenko** [comment]
@Secrus @ALERTua can you help to fix this pls

**Comment by drtwisted** [comment]
Ping? Any updates on this?

**Comment by ALERTua** [comment]
kind reminder

**Comment by Secrus** [comment]
Once it is rebased and pipelines are green I don't see any issue with merging it.

**Comment by ALERTua** [comment]
@OleksiiGerasymenko ping :)

**Review by Secrus — APPROVED** [review]

**Comment by OleksiiGerasymenko** [comment]
thanks!

**Pull request merged**
