### PR TITLE
Replace hardcoded time units with named constants

### PR DESCRIPTION
**Pull request by Minku-Koo**
- Replaced hardcoded time-related values with named constants.
- Facilitates easier adjustments of these values and reduces potential for errors.|

### CODE REVIEW

**Comment by Secrus** [comment]
Fix pre-commit checks, please.

**Comment by Minku-Koo** [comment]
I fix pre-commit, but there is some problem about rust.
In my changes, only python file is changed.

**Comment by Secrus** [comment]
Those issues are not present on the master branch, so I assume they are connected to your changes.

**Comment by Minku-Koo** [comment]
@Secrus I re-upload pull request same changes with #867

**Pull request closed without merging**
